const WindowActionTypes = {
    OPEN_WINDOW: 'OPEN_WINDOW',
    CLOSE_WINDOW: 'CLOSE_WINDOW',
    TOGGLE_WINDOW_MINIMIZED: 'TOGGLE_WINDOW_MINIMIZED',
    TOGGLE_WINDOW_ZOOM: 'TOGGLE_WINDOW_ZOOM',
    SET_WINDOW_FOCUSED: 'SET_WINDOW_FOCUSED',
    UPDATE_WINDOW_DIMENSIONS: 'UPDATE_WINDOW_DIMENSIONS',
};

export default WindowActionTypes;